const waitDb=()=>new Promise((resolve,reject)=>{if(window.IH?.db)return resolve(window.IH.db);const t=setTimeout(()=>reject(new Error('Canlı bağlantı açılamadı')),10000);addEventListener('ih-ready',()=>{clearTimeout(t);resolve(window.IH.db)},{once:true})});
const $=s=>document.querySelector(s);let db,user,character,runtime,items=[],glyphs=[];
const wounds=['Sağlam','Sarsılmış','Yaralı','Ağır Yaralı','Düştü'];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const status=t=>{const e=$('#statusMessage');if(e)e.textContent=t};
async function login(email){const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:'https://axionblooder.github.io/imparatorun-hukmu/oyuncu/index.html',shouldCreateUser:false}});status(error?'Giriş bağlantısı gönderilemedi: '+error.message:'Giriş bağlantısı e-postana gönderildi.')}
async function load(){const {data:c,error}=await db.from('characters').select('*').eq('player_user_id',user.id).maybeSingle();if(error)throw error;if(!c){$('#playerApp').hidden=true;status('Bu hesaba bağlı karakter bulunamadı. GM davetiyle giriş yaptığından emin ol.');return}character=c;$('#playerApp').hidden=false;$('#loginPanel').hidden=true;$('#characterName').textContent=c.character_name;$('#characterRace').textContent=c.race;$('#playerName').textContent=c.player_name||user.email;$('#characterConcept').textContent=c.concept||'—';$('#statBody').textContent=c.body_stat;$('#statAgility').textContent=c.agility_stat;$('#statMind').textContent=c.mind_stat;$('#statWill').textContent=c.will_stat;$('#statImpact').textContent=c.influence_stat;$('#skills').textContent=Array.isArray(c.skills)&&c.skills.length?c.skills.join(' · '):'Henüz uzmanlık girilmedi.';$('#raceChoice').textContent=c.racial_choices?.special||'—';$('#playerNotes').textContent=c.notes_player||'—';const [rr,ii,gg]=await Promise.all([db.from('character_runtime').select('*').eq('character_id',c.id).maybeSingle(),db.from('inventory_items').select('*').eq('character_id',c.id).order('created_at'),db.from('character_glyphs').select('*').eq('character_id',c.id).order('created_at')]);runtime=rr.data;items=ii.data||[];glyphs=gg.data||[];renderResources();}
function renderResources(){if(!character||!runtime)return;$('#focusValue').textContent=`${runtime.focus_current} / ${character.focus_max}`;$('#glyphCapacityValue').textContent=`${runtime.prepared_glyph_current} / ${character.prepared_glyph_max}`;$('#woundState').textContent=wounds[runtime.wound_stage]||'Sağlam';$('#knownGlyphs').innerHTML=glyphs.length?glyphs.map(g=>`<div class="resource-row"><div><strong>${esc(g.name)}</strong><small>${esc(g.description||'')}</small></div><span class="pill">Biliniyor</span></div>`).join(''):'<div class="placeholder">Henüz bilinen Glif yok.</div>';$('#inventory').innerHTML=items.length?items.map(i=>`<div class="resource-row"><div><strong>${esc(i.name)}</strong><small>${esc(i.description||'')}</small></div><div class="counter"><button data-item-minus="${i.id}">−</button><b>${i.current_quantity} / ${i.max_quantity}</b><button data-item-plus="${i.id}">+</button></div></div>`).join(''):'<div class="placeholder">Envanter boş.</div>';document.querySelectorAll('[data-item-minus]').forEach(b=>b.onclick=()=>changeItem(b.dataset.itemMinus,-1));document.querySelectorAll('[data-item-plus]').forEach(b=>b.onclick=()=>changeItem(b.dataset.itemPlus,1));}
async function changeItem(id,delta){const item=items.find(x=>x.id===id);if(!item)return;const next=Math.max(0,Math.min(item.max_quantity,item.current_quantity+delta));const {error}=await db.from('inventory_items').update({current_quantity:next}).eq('id',id);if(error)status('Eşya güncellenemedi: '+error.message);else await load();}
async function changeRuntime(field,delta,min,max){const next=Math.max(min,Math.min(max,Number(runtime[field]||0)+delta));const {error}=await db.from('character_runtime').update({[field]:next}).eq('character_id',character.id);if(error)status('Kaynak güncellenemedi: '+error.message);else await load();}
(async()=>{db=await waitDb();const {data:{session}}=await db.auth.getSession();$('#loginForm').onsubmit=e=>{e.preventDefault();login($('#loginEmail').value.trim().toLowerCase())};if(!session){$('#loginPanel').hidden=false;$('#playerApp').hidden=true;status('Davet aldığın e-posta ile giriş bağlantısı iste.');return}user=session.user;const {data:p}=await db.from('profiles').select('role').eq('id',user.id).maybeSingle();if(p?.role!=='player'){await db.auth.signOut();$('#loginPanel').hidden=false;$('#playerApp').hidden=true;status('Bu hesap oyuncu davetiyle yetkilendirilmemiş.');return}$('#logout').onclick=async()=>{await db.auth.signOut();location.reload()};await load();$('#focusMinus').onclick=()=>changeRuntime('focus_current',-1,0,character.focus_max);$('#focusPlus').onclick=()=>changeRuntime('focus_current',1,0,character.focus_max);$('#glyphMinus').onclick=()=>changeRuntime('prepared_glyph_current',-1,0,character.prepared_glyph_max);$('#glyphPlus').onclick=()=>changeRuntime('prepared_glyph_current',1,0,character.prepared_glyph_max);$('#woundMinus').onclick=()=>changeRuntime('wound_stage',-1,0,4);$('#woundPlus').onclick=()=>changeRuntime('wound_stage',1,0,4);['characters','character_runtime','inventory_items','character_glyphs'].forEach(t=>db.channel('player-'+t).on('postgres_changes',{event:'*',schema:'public',table:t},()=>load()).subscribe());status('Karakterin canlı bağlı.');})().catch(e=>status('Hata: '+e.message));
