const waitDb=()=>new Promise((resolve,reject)=>{if(window.IH?.db)return resolve(window.IH.db);const t=setTimeout(()=>reject(new Error('Canlı bağlantı açılamadı')),10000);addEventListener('ih-ready',()=>{clearTimeout(t);resolve(window.IH.db)},{once:true})});
const $=s=>document.querySelector(s);let db,token,character,runtime,items=[],glyphs=[],busy=false;
const wounds=['Sağlam','Sarsılmış','Yaralı','Ağır Yaralı','Düştü'];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const status=t=>{const e=$('#statusMessage');if(e)e.textContent=t};
function getToken(){const u=new URL(location.href);const incoming=u.searchParams.get('davet');if(incoming){localStorage.setItem('ih_player_token',incoming);u.searchParams.delete('davet');history.replaceState(null,'',u.pathname+u.search+u.hash);return incoming}return localStorage.getItem('ih_player_token')||''}
function clearAccess(message='Oyuncu bağlantısı gerekli.'){localStorage.removeItem('ih_player_token');token='';$('#playerApp').hidden=true;$('#accessPanel').hidden=false;status(message)}
async function load(silent=false){if(!token)return clearAccess();if(busy)return;busy=true;const {data,error}=await db.rpc('player_sheet_by_token',{p_token:token});busy=false;if(error){clearAccess('Bu oyuncu bağlantısı geçersiz, iptal edilmiş veya karakter silinmiş.');return}character=data?.character;runtime=data?.runtime;items=data?.items||[];glyphs=data?.glyphs||[];if(!character)return clearAccess('Karakter bulunamadı.');$('#accessPanel').hidden=true;$('#playerApp').hidden=false;$('#characterName').textContent=character.character_name;$('#characterRace').textContent=character.race;$('#playerName').textContent=character.player_name||'—';$('#characterConcept').textContent=character.concept||'—';$('#statBody').textContent=character.body_stat;$('#statAgility').textContent=character.agility_stat;$('#statMind').textContent=character.mind_stat;$('#statWill').textContent=character.will_stat;$('#statImpact').textContent=character.influence_stat;$('#skills').textContent=Array.isArray(character.skills)&&character.skills.length?character.skills.join(' · '):'Henüz uzmanlık girilmedi.';$('#raceChoice').textContent=character.racial_choices?.special||'—';$('#playerNotes').textContent=character.notes_player||'—';renderResources();if(!silent)status('Karakterin canlı bağlı.')}
function renderResources(){if(!character||!runtime)return;$('#focusValue').textContent=`${runtime.focus_current} / ${character.focus_max}`;$('#glyphCapacityValue').textContent=`${runtime.prepared_glyph_current} / ${character.prepared_glyph_max}`;$('#woundState').textContent=wounds[runtime.wound_stage]||'Sağlam';$('#knownGlyphs').innerHTML=glyphs.length?glyphs.map(g=>`<div class="resource-row"><div><strong>${esc(g.name)}</strong><small>${esc(g.description||'')}</small></div><span class="pill">Biliniyor</span></div>`).join(''):'<div class="placeholder">Henüz bilinen Glif yok.</div>';$('#inventory').innerHTML=items.length?items.map(i=>{const counter=i.consumable?`<div class="counter"><button data-item-minus="${i.id}">−</button><b>${i.current_quantity} / ${i.max_quantity}</b><button data-item-plus="${i.id}">+</button></div>`:`<div class="counter"><b>${i.current_quantity} / ${i.max_quantity}</b></div>`;return `<div class="resource-row"><div><strong>${esc(i.name)}</strong><small>${esc(i.description||'')}</small></div>${counter}</div>`}).join(''):'<div class="placeholder">Envanter boş.</div>';document.querySelectorAll('[data-item-minus]').forEach(b=>b.onclick=()=>changeItem(b.dataset.itemMinus,-1));document.querySelectorAll('[data-item-plus]').forEach(b=>b.onclick=()=>changeItem(b.dataset.itemPlus,1));}
async function changeItem(id,delta){const {error}=await db.rpc('player_adjust_item',{p_token:token,p_item_id:id,p_delta:delta});if(error)return status('Eşya güncellenemedi: '+error.message);await load(true)}
async function changeRuntime(field,delta){const {error}=await db.rpc('player_adjust_runtime',{p_token:token,p_field:field,p_delta:delta});if(error)return status('Kaynak güncellenemedi: '+error.message);await load(true)}
(async()=>{db=await waitDb();token=getToken();$('#logout').onclick=()=>{clearAccess('Bu cihazdaki oyuncu bağlantısı temizlendi.')};if(!token)return clearAccess();$('#focusMinus').onclick=()=>changeRuntime('focus_current',-1);$('#focusPlus').onclick=()=>changeRuntime('focus_current',1);$('#glyphMinus').onclick=()=>changeRuntime('prepared_glyph_current',-1);$('#glyphPlus').onclick=()=>changeRuntime('prepared_glyph_current',1);$('#woundMinus').onclick=()=>changeRuntime('wound_stage',-1);$('#woundPlus').onclick=()=>changeRuntime('wound_stage',1);await load();setInterval(()=>load(true),1000)})().catch(e=>status('Hata: '+e.message));
